# Generated by Django 4.0.4 on 2022-06-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('caption', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=20)),
            ],
        ),
    ]
